# 外传篇2-函数的异常规格说明



![Slide01](外传篇2-函数的异常规格说明.assets/Slide01.PNG)



![Slide02](外传篇2-函数的异常规格说明.assets/Slide02.PNG)



![Slide03](外传篇2-函数的异常规格说明.assets/Slide03.PNG)



![Slide04](外传篇2-函数的异常规格说明.assets/Slide04.PNG)



![Slide05](外传篇2-函数的异常规格说明.assets/Slide05.PNG)



![Slide06](外传篇2-函数的异常规格说明.assets/Slide06.PNG)



![Slide07](外传篇2-函数的异常规格说明.assets/Slide07.PNG)

```cpp
#include <iostream>

using namespace std;

void func() throw(int)
{
    cout << "func()";
    cout << endl;
    
    throw 'c';
}



int main()
{
    try 
    {
        func();
    } 
    catch(int) 
    {
        cout << "catch(int)";
        cout << endl;
    } 
    catch(char) 
    {
        cout << "catch(char)";
        cout << endl;
    }

    return 0;
}
```

![Slide08](外传篇2-函数的异常规格说明.assets/Slide08.PNG)



![Slide09](外传篇2-函数的异常规格说明.assets/Slide09.PNG)



![Slide10](外传篇2-函数的异常规格说明.assets/Slide10.PNG)

```cpp
#include <iostream>
#include <cstdlib>
#include <exception>

using namespace std;

void my_unexpected()
{
    cout << "void my_unexpected()" << endl;
    // exit(1);
    throw 1;
}

void func() throw(int)
{
    cout << "func()";
    cout << endl;
    
    throw 'c';
}

int main()
{
    set_unexpected(my_unexpected);
    
    try 
    {
        func();
    } 
    catch(int) 
    {
        cout << "catch(int)";
        cout << endl;
    } 
    catch(char) 
    {
        cout << "catch(char)";
        cout << endl;
    }

    return 0;
}
```

![Slide11](外传篇2-函数的异常规格说明.assets/Slide11.PNG)